version: "3.8"

services:
  secret_detector:
    image: secret_detector
    build: .
    working_dir: /scan
    volumes:
      - ../:/scan
    entrypoint: ["secret_detector"]
    command: ["--exclude", "build", "--exclude", ".git", "/scan"]
